// Validation diagnostic codes — must exactly match codes emitted by validator
export type FlowValidationCode =
  // Flow-level
  | 'FLOW_SOURCE_INVALID'
  | 'FLOW_SOURCE_FORBIDDEN_FIELD'
  | 'FLOW_ID_MISSING'
  | 'FLOW_VERSION_MISSING'
  | 'FLOW_TITLE_MISSING'
  | 'FLOW_DESCRIPTION_MISSING'
  | 'FLOW_ENTRY_MISSING'
  | 'FLOW_ENTRY_NOT_FOUND'
  | 'FLOW_STEPS_MISSING'
  | 'FLOW_STEPS_EMPTY'
  | 'FLOW_METADATA_INVALID'
  | 'FLOW_UNREACHABLE_STEP'
  | 'FLOW_TERMINAL_MISSING'
  | 'FLOW_TERMINAL_NOT_REACHABLE'
  | 'FLOW_SELF_LOOP_FORBIDDEN'
  | 'FLOW_CYCLE_UNSUPPORTED'
  // Step base
  | 'FLOW_STEP_INVALID'
  | 'FLOW_STEP_ID_MISSING'
  | 'FLOW_STEP_ID_MISMATCH'
  | 'FLOW_STEP_TYPE_MISSING'
  | 'FLOW_STEP_SUBTYPE_MISSING'
  | 'FLOW_STEP_TITLE_MISSING'
  | 'FLOW_STEP_DESCRIPTION_MISSING'
  | 'FLOW_STEP_FORBIDDEN_FIELD'
  | 'FLOW_STEP_NEXT_MISSING'
  | 'FLOW_INVALID_TYPE'
  | 'FLOW_INVALID_SUBTYPE'
  // Transitions
  | 'FLOW_TRANSITION_NOT_FOUND'
  // PROCESS/DATA
  | 'FLOW_DATA_ARTEFACT_MISSING'
  | 'FLOW_DATA_STEP_FORBIDDEN_FIELD'
  // CONTROL/ROUTE
  | 'FLOW_ROUTE_FACTREF_REMOVED'
  | 'FLOW_ROUTE_DECISIONSETID_REMOVED'
  | 'FLOW_ROUTE_REF_MISSING'
  | 'FLOW_ROUTE_REF_INVALID'
  | 'FLOW_ROUTE_CASES_MISSING'
  | 'FLOW_ROUTE_DEFAULT_MISSING'
  // EFFECT
  | 'FLOW_EFFECT_OPERATION_MISSING'
  | 'FLOW_EFFECT_INPUT_MISSING'
  | 'FLOW_EFFECT_INPUT_INVALID'
  | 'FLOW_EFFECT_ON_ERROR_MISSING'
  | 'FLOW_OBJECT_INPUTREF_REMOVED'
  | 'FLOW_SUBFLOW_FLOW_ID_MISSING'
  | 'FLOW_SUBFLOW_FLOW_VERSION_MISSING'
  // WAIT
  | 'FLOW_WAIT_SOURCE_MISSING'
  | 'FLOW_WAIT_SOURCE_NOT_EFFECT'
  | 'FLOW_WAIT_SOURCE_TRANSITION_MISMATCH'
  | 'FLOW_WAIT_ERROR_MISSING'
  | 'FLOW_WAIT_TIMEOUT_MISSING'
  | 'FLOW_CALL_WAIT_UNSUPPORTED'
  // TERMINAL
  | 'FLOW_TERMINAL_RESULT_AMBIGUOUS'
  | 'FLOW_TERMINAL_RESULT_MISSING'
  | 'FLOW_TERMINAL_RESULTREF_INVALID'
  | 'FLOW_TERMINAL_RESULT_NOT_JSON_SAFE'
  | 'FLOW_TERMINAL_RESULT_STATUS_MISSING'
  | 'FLOW_TERMINAL_RESULT_STATUS_MISMATCH'
  | 'FLOW_TERMINAL_RESULT_OUTCOME_MISSING';

// Runtime error codes
export type FlowRuntimeCode =
  | 'FLOW_STATE_INVALID'
  | 'FLOW_STATE_V1_FORBIDDEN'
  | 'FLOW_CONTEXT_FORBIDDEN'
  | 'FLOW_CONTEXT_EFFECTS_FORBIDDEN'
  | 'FLOW_WAIT_RESULT_PERSISTED_FORBIDDEN'
  | 'FLOW_STEP_EXECUTION_INVALID'
  | 'FLOW_TIMELINE_INVALID'
  | 'FLOW_RESUME_EVENT_INVALID'
  | 'FLOW_STEP_NOT_FOUND'
  | 'FLOW_STEP_MISMATCH'
  | 'FLOW_STEP_ID_MISMATCH'
  | 'FLOW_FLOW_MISMATCH'
  | 'FLOW_TERMINAL_MISUSED'
  | 'FLOW_REDUCE_INVALID_TYPE'
  | 'FLOW_APPLY_INVALID_TYPE'
  | 'FLOW_RESUME_INVALID_TYPE'
  | 'FLOW_ROUTING_VALUE_INVALID'
  | 'FLOW_RESULT_SHAPE_INVALID'
  | 'FLOW_MIXED_RESULT'
  | 'FLOW_PATH_NOT_RESOLVED'
  | 'FLOW_REQUEST_ID_MISSING'
  | 'FLOW_RESUME_REQUEST_ID_MISMATCH'
  | 'FLOW_RESULT_REF_NOT_RESOLVED'
  | 'FLOW_RESULT_REF_SHAPE_INVALID'
  // ROUTE
  | 'FLOW_ROUTE_REF_NOT_RESOLVED'
  | 'FLOW_ROUTE_REF_NOT_SCALAR'
  // DATA
  | 'FLOW_DATA_OUTPUT_INVALID'
  | 'FLOW_DATA_WRITE_INVALID'
  | 'FLOW_DATA_WRITE_FORBIDDEN_PATH'
  | 'FLOW_DATA_WRITE_NOT_JSON_SAFE'
  | 'FLOW_RUNTIME_INPUT_INVALID';

export type FlowCompileCode = 'FLOW_PREPARE_INVALID';
export type FlowErrorCode = FlowValidationCode | FlowRuntimeCode | FlowCompileCode;

export interface ValidationIssue {
  code: string;
  message: string;
  path?: string;
  details?: Record<string, unknown>;
}

export interface ValidationResult {
  ok: boolean;
  issues: ValidationIssue[];
}
